#!/bin/bash
#
# Common config file, that gets sourced by others.

# fetch our external hostname from ec2 metadata.
EXTERNAL_HOSTNAME=$(curl --connect-timeout 1 --silent http://169.254.169.254/latest/meta-data/public-hostname)

# And if we timeout, eg. non-ec2 instance, we just use our "internal"
if [ "$EXTERNAL_HOSTNAME" = "" ] ; then
	EXTERNAL_HOSTNAME=$HOSTNAME
fi

# cloud-init doesn't set HOME, so set it
export HOME=$(getent passwd $(id -u) | cut -d: -f 6)

# Email settings
RECIPENT_EMAIL_ADDRESS=anton@dohi.se
SENDER_EMAIL_ADDRESS=ckan-root@openumea.se
#EMAIL_CREDENTIALS=XXXXXXXXXXXXXXXXXXXX:YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
#RELAY_HOST=email-smtp.us-east-1.amazonaws.com:587

# Where cloud data is stored
CLOUD_DATA=/var/lib/cloud/data/datafiles
mkdir -p $CLOUD_DATA

# What shall we call this ckan instance?
CKAN_HOSTNAME=ckan.openumea.se

# Where is the ckan root?
CKAN_ROOT=/var/www/ckan
CKAN_VENV=$CKAN_ROOT/pyenv

# What shall we call the ckan cfg file?
# DEFAULT: development.ini
CKAN_CFG=$CKAN_ROOT/development.ini

# Should we apply a theme?
#CKAN_THEME=openumea-theme

# To what bucket should we do backup's?
DB_BACKUP_S3_BUCKET="openumea-backups"

# What db-backup should we restore?
# Use http/https signed url to s3 or s3://bucket/key..
CKAN_BACKUP="s3://$DB_BACKUP_S3_BUCKET/$CKAN_HOSTNAME/ckan-YYYYMMDD-HH:MM.pg_dump.gz"

# In what bucket do we store our files?
CKAN_STORAGE_BUCKET=openumea-storage

# or, if we are not restoring a backup, create a initial systadmin:
#CKAN_SYSADMIN_USER=sysadm
#CKAN_SYSADMIN_PW=sysadm

# From what repo should we fetch cronjobs?
CRONJOBS_REPO=openumea-cronjobs

# And where do we store credentials for cronjobs? eg. cronjobs.cfg
CREDENTIALS_BUCKET=openumea-credentials

# Should we enable datastore?
#DATASTORE=0

# Should we restore a datastore backup?
#DATASTORE_BACKUP="s3://$DB_BACKUP_S3_BUCKET/$CKAN_HOSTNAME/datastore-YYYYMMDD-HH:MM.pg_dump.gz"
